name: pytest
on: workflow_dispatch

jobs:
  pytest:
    runs-on: ubuntu-24.04
    steps:
      - name: pre - checkout
        run: |
          pwd
          ls -lh
      - name: checkout code
        uses: actions/checkout@v3
        #run: |
        #  git clone https://github.com/albert157255/github-action-python
        #  cd github-action-python
      - name: after - checkout
        run: |
          pwd
          ls -lh
      - name: Install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
